volumes:
    postgres-data:
        external: true
    pgadmin:
        external: true
services:
    postgres:
        image: postgres:14.2-bullseye
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_MULTIPLE_DATABASES=subscriptions,products
            - POSTGRES_PASSWORD=test-databases
        ports:
            - 15432:5432
    products:
        build:
            context: ./products
            dockerfile: ./Dockerfile.dev
        ports:
            - "8080:8000"
        volumes:
            - ./products:/app
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://products:password@postgres:5432/products
            WAIT_HOSTS: postgres:5432
            WAIT_TIMEOUT: 240
    subscriptions:
        build:
            context: ./subscriptions/api
            dockerfile: ./Dockerfile.dev
        ports:
            - "8200:8000"
        volumes:
            - ./subscriptions/api:/app
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://subscriptions:password@postgres:5432/subscriptions
            WAIT_HOSTS: postgres:5432
            WAIT_TIMEOUT: 240
    subscriptions-poller:
        build:
            context: ./subscriptions/poll
            dockerfile: ./Dockerfile.dev
        volumes:
            - ./subscriptions/poll:/app
            - ./subscriptions/api/subscriptions_rest:/app/subscriptions_rest
            - ./subscriptions/api/subscriptions:/app/subscriptions
        depends_on:
            - postgres
            - subscriptions
        environment:
            DATABASE_URL: postgres://subscriptions:password@postgres:5432/subscriptions
            WAIT_HOSTS: postgres:5432,subscriptions:8000
            WAIT_TIMEOUT: 240
    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            REACT_APP_SUBSCRIPTIONS: http://localhost:8200
            REACT_APP_SUBSCRIPTIONS_POLLER: http://localhost:8100
            REACT_APP_PRODUCTS: http://localhost:8080
    pgadmin:
        image: dpage/pgadmin4
        volumes:
            - /pgadmin/var/lib/pgadmin4
        ports:
            - "8060:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: 'rbbitphoto@gmail.com'
            PGADMIN_DEFAULT_PASSWORD: 'password'
