volumes:
    postgres-data:
        external: true
services:
    postgres:
        build:
            context: ./relational-data
            dockerfile: ./Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES=users,products,clothing,subscriptions
            - POSTGRES_PASSWORD=test-databases
        ports:
            - 15432:5432
    products:
        build:
            context: ./products
            dockerfile: ./Dockerfile.dev
        ports:
            - "8080:8000"
        volumes:
            - ./products:/app
        environment:
            DATABASE_URL: postgresql://user-name:password@postgres/products
            WAIT_HOSTS: postgres:5432
    users:
        build:
            context: ./users
            dockerfile: ./Dockerfile.dev
        ports:
            - "8100:8000"
        volumes:
            - ./users:/app
        environment:
            DATABASE_URL: postgresql://user-name:password@postgres/users
            WAIT_HOSTS: postgres:5432

    subscriptiopns:
        build:
            context: ./subscriptions
            dockerfile: ./Dockerfile.dev
        ports:
            - "8200:8000"
        volumes:
            - ./subscriptions:/app
        environment:
            DATABASE_URL: postgresql://user-name:password@postgres/users
            WAIT_HOSTS: postgres:5432