volumes:
  postgres-data:
    external: true
services:
  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=users,products,clothing,subscriptions
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
  products:
    build:
      context: ./products
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./products:/app
    environment:
      DATABASE_URL: postgresql://products:password@postgres/products
      WAIT_HOSTS: postgres:5432

  subscriptions:
    build:
      context: ./subscriptions
      dockerfile: ./Dockerfile.dev
    ports:
      - "8200:8000"
    volumes:
      - ./subscriptions:/app
    environment:
      DATABASE_URL: postgresql://subscriptions:password@postgres/subscriptions
      WAIT_HOSTS: postgres:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_USERS: http://localhost:8100
      REACT_APP_SUBSCRIPTIONS: http://localhost:8200
      REACT_APP_CLOTHING: http://localhost:8210
      REACT_APP_PRODUCTS: http://localhost:8080
